#cloud-config
write_files:
  - content: |
      #!/bin/sh
      export CI_LHN=${tf_loc_hostname}
      export CI_LIP4=${tf_loc_ip_v4}
      export CI_DOT_REPO=${tf_dot_repo}
      export CI_DOT_BRANCH=${tf_dot_branch}
      export HOME=/root
      echo `date`: command $0 is starting
      apt-get update && \
      apt-get install -y --no-install-recommends git virtualenv fail2ban python3-systemd && \
      mkdir -p /root/clinit /root/locgit && cd /root/locgit && \
      git clone --single-branch --branch $CI_DOT_BRANCH $CI_DOT_REPO && \
      cd otvl_dvoptls/vault_server && virtualenv venv && \
      venv/bin/pip install -r requirements.txt && \
      systemctl daemon-reload && \
      systemctl enable svault_server && \
      systemctl start svault_server && \
      true || exit 1
      echo `date`: command $0 is exiting
      exit 0
    path: /root/bin/otvl_cloud_init.sh
    owner: root:root
    permissions: '0750'
  - content: |
      [Unit]
      Description=Runs vlts server
      [Service]
      Environment="PYTHONPATH=src"
      ExecStart=venv/bin/python -m vault_server -u 9080 --log-config src/vault_server/log_config.yml
      WorkingDirectory=/root/locgit/otvl_dvoptls/vault_server
      Restart=always
      RestartSec=20s
      [Install]
      WantedBy=multi-user.target
    path: /etc/systemd/system/svault_server.service
    permissions: '0644'
  - content: |
      [DEFAULT]
      # Debian 12 has no log files, just journalctl
      backend = systemd
      # "bantime" is the number of seconds that a host is banned.
      bantime  = 1d
      # "maxretry" is the number of failures before a host get banned.
      maxretry = 5
      # A host is banned if it has generated "maxretry" during the last "findtime"
      findtime  = 1h
      [sshd]
      enabled = true
    path: /etc/fail2ban/jail.local
    permissions: '0644'
runcmd:
  - [ /root/bin/otvl_cloud_init.sh ]
