---
# sk3s_server/tasks/main.yml

- name: Create rancher/k3s configuration directory
  file:
    path: "/etc/rancher/k3s"
    state: directory
    mode: 0755

- name: Configure rancher/k3s TLS SAN in /etc/rancher/k3s/config.yaml
  template:
    src: rancher-config.yaml
    dest: /etc/rancher/k3s/config.yaml

###