images:
  reg: registry:2.8
  traefik: traefik:v3.4.3
uid: 3002
fs_group: 2002
resources:
  requests:
    cpu: "50m"
    memory: 128Mi
  limits:
    cpu: "1"
    memory: 512Mi
ingress:
  enabled: true
  # host: otvl-ctr.example.com, defaults to <release-name>.example.com
  # alt_host: alt-otvl-ctr.example.com, defaults to alt-<release-name>.example.com
apr_credentials: "ctrlogin:"
