---
# services/code_server/user_home/tasks/main.yml

- name: Loop over code_server items for user home create
  include_tasks: uh_item.yml
  loop: "{{ cv.code_server_items }}"
  loop_control:
    loop_var: current_item

###