---
# services/code_server/user_home/tasks/uh_item.yml

- name: Create sync server home directory
  file:
    path: /data/home
    state: directory
    owner: root
    group: root
    mode: 0711
  become: true

- name: Create sync server home/{{ current_item.user }} directory
  file:
    path: "/data/home/{{ current_item.user }}"
    state: directory
    owner: "{{ current_item.user }}"
    group: "{{ current_item.user }}"
    mode: 0750
  become: true

###