---
# services/vdaserver/tasks/main.yml

- name: Create a group "{{ cv.vdasync.user }}"
  ansible.builtin.group:
    name: "{{ cv.vdasync.user }}"
    gid: "{{ cv.vdasync.uid }}"

- name: Create a user "{{ cv.vdasync.user }}"
  ansible.builtin.user:
    name: "{{ cv.vdasync.user }}"
    uid: "{{ cv.vdasync.uid }}"
    group: "{{ cv.vdasync.user }}"
    groups:
    - "{{ remote_user }}"
    home: "/data/home/{{ cv.vdasync.user }}"
    create_home: false
    shell: /bin/bash

- name: Create vdasync server /home/{{ cv.vdasync.user }}/htd directory
  file:
    path: "/data/home/{{ cv.vdasync.user }}/{{ item }}"
    state: directory
    owner: "{{ cv.vdasync.user }}"
    group: "{{ cv.vdasync.user }}"
    mode: 0750
  with_items:
    - home
    - tools
    - data

- name: Install vdasync utilities on the file server host
  include_role:
    name: commons
    tasks_from: install_from_ghr
  vars:
    url: "{{ cv.vdasync.release_url }}"
    tgz_name: "vdasync.1.tgz"
    sha: "{{ cv.vdasync.sha }}"
    dir_content: true
    binary_name: "vdasync"
    binary_path: "."
    dest_dir_content: "/usr/local/bin"

- name: "Create vdaserver systemd service file"
  template:
    src: systemd/vdaserver.service
    dest: /etc/systemd/system/vdaserver.service
    owner: root
    group: root
    mode: 0644
  register: vdas_config

- name: Create and run systemd service for vdaserver
  block:
    - name: Enable vdaserver systemd service
      systemd:
        name: "vdaserver"
        enabled: yes
    - name: Restart vdaserver systemd service
      systemd:
        name: "vdaserver"
        state: restarted
        daemon_reload: yes
  when: vdas_config.changed

- name: "Create vdatserver systemd service file"
  template:
    src: systemd/vdatserver.service
    dest: /etc/systemd/system/vdatserver.service
    owner: root
    group: root
    mode: 0644
  register: vdats_config

- name: Create and run systemd service for vdatserver
  block:
    - name: Enable vdatserver systemd service
      systemd:
        name: "vdatserver"
        enabled: yes
    - name: Restart vdatserver systemd service
      systemd:
        name: "vdatserver"
        state: restarted
        daemon_reload: yes
  when: vdats_config.changed

###