# commons/tasks/docker_build.yml
# run docker build, tag and push to registry
# vars:
#   dkb_message: message to be displayed during docker build
#   dkb_cmd_dir: docker build command directory
#   dkb_arg_dir: docker build argument directory, defaults to "."
#   dkb_add_args: docker build additional arguments defaults to ""
#   docker_file: docker file defaults to Dockerfile in build directory
#   image: image name and version to tag and push
#

- name: set role's variables
  block:
    - name: Set command line w/o dockerfile
      set_fact:
        dkb_cmdline: "docker build {{ dkb_add_args | default('') }} -t {{ cv.ctr.ingress_host }}/{{ image }} {{ dkb_arg_dir | default('.') }}"
      when: docker_file | default("") == ""
    - name: Set command line with dockerfile
      set_fact:
        dkb_cmdline: "docker build -f {{ docker_file }} {{ dkb_add_args | default('') }} -t {{ cv.ctr.ingress_host }}/{{ image }} {{ dkb_arg_dir | default('.') }}"
      when: docker_file | default("") != ""

- name: "{{ dkb_message }}"
  block:
    - command:
        chdir: "{{ dkb_cmd_dir }}"
        cmd: "{{ dkb_cmdline }}"
      register: dkb
    - debug: var=dkb.cmd
    - debug: var=dkb.stderr_lines
    - debug: var=dkb.stdout_lines

- name: "docker login {{ cv.ctr.ingress_host }}"
  block:
    - command:
        cmd: "docker login {{ cv.ctr.ingress_host }} -u {{ cv.ctr.login }} --password-stdin"
        stdin: "{{ cv.ctr.password }}"
      register: dkbl
    - debug: var=dkbl.cmd
    - debug: var=dkbl.stderr_lines
    - debug: var=dkbl.stdout_lines

- name: "docker push {{ cv.ctr.ingress_host }}/{{ image }}"
  block:
    - command:
        cmd: "docker push {{ cv.ctr.ingress_host }}/{{ image }}"
      register: dkbp
    - debug: var=dkbp.cmd
    - debug: var=dkbp.stderr_lines
    - debug: var=dkbp.stdout_lines
