# commons/tasks/helm_release.yml
# install helm release from local repo and ansible template instanciated
# vars:
#   title: name what is to be deployed
#   chart_sp: repository sub-path in devops src/helm
#   vf_template_sp: repository sub-path for the values file template (in devops src/ansible/otvl/templates/override/helm)
#   release_name: Helm release name
#   uninstall: uninstalls the release if present and true
#   helm_opts: helm 

- name: set included vars
  set_fact:
    hr_hvd: "{{ remote_user_home }}/helm_values"

- name: Instantiate the template {{ vf_template_sp }} as a local values file {{ hr_hvd }}
  template:
    src: "{{ playbook_dir }}/../lops_repo/helm/{{ install_env }}/{{ vf_template_sp }}"
    dest: "{{ hr_hvd }}/{{ release_name }}.yaml"
    mode: 0600

- name: Uninstall {{ title }}
  kubernetes.core.helm:
    name: "{{ release_name }}"
    release_namespace: "{{ cv.k3s.default_namespace }}"
    chart_ref: "{{ playbook_dir }}/../helm/{{ chart_sp }}"
    state: absent
    wait: true
  when: uninstall | default(false)

- name: Install {{ title }}
  kubernetes.core.helm:
    name: "{{ release_name }}"
    release_namespace: "{{ cv.k3s.default_namespace }}"
    chart_ref: "{{ playbook_dir }}/../helm/{{ chart_sp }}"
    values_files:
      - "{{ hr_hvd }}/{{ release_name }}.yaml"
