# commons/tasks/kapply_from_url.yml
# kubectl apply manifest downloaded from url
# vars:
#   url: url
#   sha: sha256sum of the downloaded file
#   dload_name: downloaded file name
#   kapp_message: message to be displayed during kubectl apply

- name: set delivery directory for downloads
  block:
    - name: Does {{ cv.config_paths.delivery }} exist
      stat:
        path: "{{ cv.config_paths.delivery }}"
      register: kfu_dlv_stat
    - name: Set delivery to {{ cv.config_paths.delivery }}
      set_fact:
        kfu_dlv: "{{ cv.config_paths.delivery }}"
      when: kfu_dlv_stat.stat.exists
    - name: Set delivery to /tmp
      set_fact:
        kfu_dlv: "/tmp"
      when: not kfu_dlv_stat.stat.exists

- name: set included vars
  set_fact:
    kfu_get_msg: "Download {{ dload_name }} in {{ kfu_dlv }} from {{ url }}"

- name: "{{ kfu_get_msg }}"
  ansible.builtin.get_url:
    url: "{{ url }}"
    dest: "{{ kfu_dlv }}/{{ dload_name }}"
    checksum: "sha256:{{ sha }}"
  become: yes
  register: kfu_downl

- name: "{{ kapp_message }}"
  block:
    - debug: var=kapp_message
    - command:
        cmd: "kubectl apply -f {{ kfu_dlv }}/{{ dload_name }}"
      register: kapply
    - debug: var=kapply.cmd
    - debug: var=kapply.stderr_lines
    - debug: var=kapply.stdout_lines
  when: kfu_downl.changed
