---
dv:
  debug: false
  prod: true
  config_paths:
    delivery: /otvl/delivery
    data: /otvl/data
  localhosts: []
    # fqdn: local-network-ip
    # eg:
    # t-sk3s-sv-loc: "172.25.0.7"
  containerd:
    release_url: "https://github.com/containerd/containerd/releases/download/v2.2.2/containerd-2.2.2-linux-amd64.tar.gz"
    sha: "2c08c99cbde73b3388c6d5da68e0bcaebc70c9174f2b14d785695e4401b3ede0"
  runc:
    release_url: "https://github.com/opencontainers/runc/releases/download/v1.3.5/runc.amd64"
    sha: "bd843d75a788e612c9df286b1fa519a44fcbb7a7b8d01e2268431433cc7c718c"
  cni_plugins:
    release_url: "https://github.com/containernetworking/plugins/releases/download/v1.9.1/cni-plugins-linux-amd64-v1.9.1.tgz"
    sha: "b98f74a0f8522f0a83867178729c1aa70f2158f90c45a2ca8fa791db1c76b303"
  nerdctl:
    release_url: "https://github.com/containerd/nerdctl/releases/download/v2.2.1/nerdctl-2.2.1-linux-amd64.tar.gz"
    sha: "34144de7f12756aa4b9dc42a907fd95b0c5eb82a63566a650ca10c8abe7a26a0"
  buildkit:
    release_url: "https://github.com/moby/buildkit/releases/download/v0.28.1/buildkit-v0.28.1.linux-amd64.tar.gz"
    sha: "2e84057b941488c54575aee57015681f08c71042bd20c739b23879dfad3f2449"
  kubectl:
    url: "https://dl.k8s.io/v1.35.1/bin/linux/amd64/kubectl"
    sha: "36e2f4ac66259232341dd7866952d64a958846470f6a9a6a813b9117bd965207"
  cmctl:
    release_url: "https://github.com/cert-manager/cmctl/releases/download/v2.4.1/cmctl_linux_amd64.tar.gz"
    sha: "78e66db213d95604e9072c34d3424d3667cbc92fc852e8e39acb6942742cb7e5"
  helm:
    release_url: "https://get.helm.sh/helm-v3.20.1-linux-amd64.tar.gz"
    sha: "0165ee4a2db012cc657381001e593e981f42aa5707acdd50658326790c9d0dc3"
  k9s:
    release_url: "https://github.com/derailed/k9s/releases/download/v0.50.18/k9s_Linux_amd64.tar.gz"
    sha: "0b697ed4aa80997f7de4deeed6f1fba73df191b28bf691b1f28d2f45fa2a9e9b"
  opentofu:
    release_url: "https://github.com/opentofu/opentofu/releases/download/v1.11.5/tofu_1.11.5_linux_amd64.tar.gz"
    sha: "e73868ab8abaca15d3c974dcf6a5e878860d6f2212867433aa3d8f2b43a492d9"
  cert_manager:
    release_url: "https://github.com/cert-manager/cert-manager/releases/download/v1.20.2/cert-manager.yaml"
    sha: "1ce11cae912adecc69e6bb623435fafc9ed21505f9efff98bd71d7b80f01db1f"
    le_url: "https://acme-v02.api.letsencrypt.org/directory"
    le_email: "acme@example.com"
  k3s:
    # hostname of the api server in a simple cluster
    # sc_api_server:
    # docker: false
    traefik:
      customize: true
    default_namespace: "default"
  ctr:
    # release: ctr
    # skip_hdeploy: false
    # helm_uninstall: false
    # uid: 2001
    # fs_group: 2001
    # ingress_host: ctr.example.com
    # ingress_alt_host: alt-ctr.example.com
    # login: everybody
    # password: knows
    # apr_credentials: "everybody:$apr1$hd/Cq048$bx71KTBads2TZYNhCVzja1"
  traefik:
    image: "traefik:v3.4"
  vdasync:
    release_url: "https://github.com/t-beigbeder/vdasync/releases/download/v0.17.1/vdasync-linux-amd64-v0.17.1.tgz"
    sha: "3b9bdab05c13dcba10759ad450ffc0f11feeb1ee0a4b50ef476780e8d6c13bdc"
    server_fqdn: vdaserver.example.com
    server_port: 443
    uid: 2002
    user: vdaserver
  build:
    vm: build-hostname
    ssh:
      user: build-user
      uid: build-uid
      pub: "ssh-ed25519 pubkey id-ed-build"
      pri: "id-ed-build file content"
  # gpu_operator: false
  dv_ops:
    image: dv-ops:1.1.0
  dv_dev_tools:
    image: dv-dev-tools:1.5.1
  theia:
    image:
      name: theia-build
      version: "1.66.2-p6"
  dv_ide:
    image:
      name: dv-cs
      upstream_version: "4.125.0" # don't prefix with v!
      version: "4.125.0-p2"
  postgres:
    image: postgres:18.1
  pg_cli:
    image: otvl-pg-cli:18.1
  k8s_clients:
    image: k8s-clients:1.3.0
  workflow_task:
    image: workflow-task:0.12
  code_server_items:
  dv_secrets:
    postgres_passwd: postgres_passwd_value
    aws_access_key_id: aws_access_key_id_value
    aws_secret_access_key: aws_secret_access_key_value
    s3_tests_access_key_id: s3_tests_access_key_id_value
    s3_tests_secret_access_key: s3_tests_secret_access_key_value
  # ======================================================
  # DEV PG instances
  dspg_items:
  # ======================================================
  # DEV IDEs
  dv_ide_items:
  # - image: "lscr.io/linuxserver/code-server:4.101.1"
    # release: code-server
    # skip_hdeploy: false
    # helm_uninstall: false
    # ingress_host: code-server.example.com
    # uid: 2025
    # user: everybody
    # # renew: openssl passwd -apr1
    # apr_password: "$apr1$hd/Cq048$bx71KTBads2TZYNhCVzja1"
    # sync_server: sync-server
    # dns_resolv_content: base64 for overwritting /etc/resolv.conf
    # ext_hosts_aliases: true
    # node_label: with-this-gpu
    # kubeconfig: true
  ows_build: false
  ows_apache_image: "ows-apache:1.3"
  ows_sync_image: "ows-sync:1.4"
  ows:
    ssh:
      user: build-user
      uid: build-uid
      pub: "ssh-ed25519 pubkey id-ed-build"
      pri: "id-ed-build file content"
  otvl_web_services:
#  - release: blog-test
#    skip_hdeploy: false
#    helm_uninstall: true
#    ingress_host: t-blog.example.com
#    grepo: https://github.com/repo_for_site
#    gbranch: br
#    srepo: ssh-user@ssh-host:/path/to/5a7
###
  awf_post:
    skip_hdeploy: true
    helm_uninstall: true
  mockup:
    # lbs_build: false
    lbs:
      image: label-studio:1.21-p2
    otvl_lbs_services:
