apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-production
spec:
  acme:
    email: "{{ cv.cert_manager.le_email }}"
    server: "{{ cv.cert_manager.le_url }}"
    privateKeySecretRef:
      # Secret resource that will be used to store the account's private key.
      name: letsencrypt-staging-issuer-account-key
    solvers:
      - http01:
          ingress:
            class: traefik
