apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-proxy-cmap
data:
  "static-config.yml": |
    global:
      sendAnonymousUsage: true
    log:
      level: INFO
    accessLog:
      format: json
      fields:
        defaultMode: keep
    providers:
      file:
        filename: /traefik/dynamic-conf.yml
        watch: true
    entryPoints:
      web:
        address: ':5000'

  "dynamic-conf.yml": |
    http:
      routers:
{{- range $index, $url := .Values.private_prefixes }}
        to-app-private{{ $index }}:
          rule: "PathPrefix(`{{ $url }}`)"
          middlewares:
            - basic-auth
            - https-header
          service: ows
{{- end }}
        to-app:
          rule: "PathPrefix(`/`)"
          middlewares:
            - https-header
          service: ows
      middlewares:
{{- if .Values.apr_credentials }}
        basic-auth:
          basicAuth:
            users:
              - "{{ .Values.apr_credentials }}"
{{- end }}
        https-header:
          headers:
            customRequestHeaders:
              X-Forwarded-Proto: "https"
      services:
        "ows":
          loadBalancer:
            servers:
              - url: "http://{{ .Release.Name }}-ows:80"
