---
# services/code_server/user_login/tasks/main.yml

- name: Loop over code_server items for user login create
  include_tasks: ul_item.yml
  loop: "{{ cv.code_server_items }}"
  loop_control:
    loop_var: current_item

###