apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: traefik
  namespace: kube-system
spec:
  # https://github.com/traefik/traefik-helm-chart/blob/master/traefik/values.yamlq
  valuesContent: |-
    persistence:
      enabled: true
    logs:
      general:
        level: INFO
      access:
        enabled: false
    
    ports:
      web:
        redirectTo:
          port: websecure
          # enable cert-manager to bypass redirection during http challenge
          priority: 1000
        transport:
          respondingTimeouts:
            idleTimeout: 180
