apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: traefik
  namespace: kube-system
spec:
  # https://github.com/traefik/traefik-helm-chart/blob/master/traefik/values.yaml
  valuesContent: |-
    persistence:
      enabled: true
    logs:
      general:
        level: INFO
      access:
        enabled: false
    
    ports:
      web:
        redirections:
          entryPoint:
            to: websecure
            scheme: https
            permanent: true
            # enable cert-manager to bypass redirection during http challenge   
            priority: 1000
      websecure:
        transport:
          respondingTimeouts:
            readTimeout: 300
