---
# mockups/roles/buildkit/tasks/main.yml

- name: Here mockups/roles/buildkit/tasks/main.yml
  include_role:
    name: commons
    tasks_from: install_from_ghr
  vars:
    url: "{{ cv.buildkit.release_url }}"
    tgz_name: "buildkit.3.tgz"
    sha: "{{ cv.buildkit.sha }}"
    binary_name: "buildkit"
    binary_path: "bin"
    dir_content: true
    dest_dir_content: "/usr/local"

- name: Create the buildkit configuration directory
  file:
    dest: "/etc/buildkit"
    state: directory
    mode: 0755

- name: Create the buildkit configuration file
  template:
    src: "etc/buildkitd.toml"
    dest: "/etc/buildkit/buildkitd.toml"
    mode: 0644

- name: "Create buildkit systemd service file"
  template:
    src: systemd/buildkit.service
    dest: /etc/systemd/system/buildkit.service
    owner: root
    group: root
    mode: 0644
  register: buildkit_config

- name: Create and run systemd service for buildkit
  block:
    - name: Enable buildkit systemd service
      systemd:
        name: "buildkit"
        enabled: yes
    - name: Restart buildkit systemd service
      systemd:
        name: "buildkit"
        state: restarted
        daemon_reload: yes
  when: buildkit_config.changed

###