---
# services/code_server/tasks/main.yml

- name: Loop over code_server items for release with helm
  include_tasks: release_cs_item.yml
  loop: "{{ cv.code_server_items }}"
  loop_control:
    loop_var: current_item

###