apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-cs
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Release.Name }}-cs
  strategy:
    type: Recreate
  template:
    metadata:
      name: {{ .Release.Name }}-cs
      labels:
        app.kubernetes.io/name: {{ .Release.Name }}-cs
    spec:
      securityContext:
        runAsUser: {{ .Values.uid }}
        runAsGroup: {{ .Values.uid }}
      containers:
        - name: code-server
          image: {{ .Values.images.codeserver }}
          env:
          - name: TZ
            value: Etc/UTC
          - name: USER
            value: {{ .Values.user }}
          - name: HOME
            value: /home/{{ .Values.user }}
          command:
            # https://github.com/linuxserver/docker-code-server/blob/master/root/etc/s6-overlay/s6-rc.d/svc-code-server/run
            - /usr/local/bin/code-server
            - --bind-addr
            - "0.0.0.0:8443"
            - --disable-telemetry
            - --auth
            - "none"
            - --app-name
            - code-server-for-{{ .Values.user }}
          volumeMounts:
          - mountPath: /home/{{ .Values.user }}
            name: home-volume
          - mountPath: /tools/{{ .Values.user }}
            name: tools-volume
          - mountPath: /data/{{ .Values.user }}
            name: data-volume
          - mountPath: /local
            name: ephemeral-volume
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          ports:
            - containerPort: 8443
          livenessProbe:
            periodSeconds: 60
            timeoutSeconds: 2
            httpGet:
              path: /
              port: 8443
          readinessProbe:
            periodSeconds: 60
            timeoutSeconds: 2
            httpGet:
              path: /
              port: 8443
{{- if .Values.node_label -}}
      nodeSelector:
        otvl-agent: {{ .Values.node_label }}
{{- end }}
      volumes:
      - name: home-volume
        emptyDir:
      - name: tools-volume
        emptyDir:
      - name: data-volume
        emptyDir:
      - name: ephemeral-volume
        emptyDir:
      tolerations:
      - key: "agent-deploy"
        value: "true"
        effect: "NoExecute"
      restartPolicy: Always
