apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-cs
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Release.Name }}-cs
  strategy:
    type: Recreate
  template:
    metadata:
      name: {{ .Release.Name }}-cs
      labels:
        app.kubernetes.io/name: {{ .Release.Name }}-cs
    spec:
      securityContext:
        runAsUser: {{ .Values.uid }}
        runAsGroup: {{ .Values.uid }}
        fsGroup: {{ .Values.fs_group }}
      containers:
        - name: code-server
          image: {{ .Values.images.codeserver }}
          env:
          - name: TZ
            value: Etc/UTC
          volumeMounts:
          - mountPath: /config
            name: data-volume
            subPath: home/debian
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          ports:
            - containerPort: 8443
          livenessProbe:
            periodSeconds: 60
            httpGet:
              path: /
              port: 8443
          readinessProbe:
            periodSeconds: 60
            httpGet:
              path: /
              port: 8443
      volumes:
      - name: data-volume
        nfs:
          # FIXME
          server: t-k3s-sv-loc
          path: /data
      tolerations:
      - key: "agent-deploy"
        value: "true"
        effect: "NoExecute"
      restartPolicy: Always
