apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-cs
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Release.Name }}-cs
  strategy:
    type: Recreate
  template:
    metadata:
      name: {{ .Release.Name }}-cs
      labels:
        app.kubernetes.io/name: {{ .Release.Name }}-cs
    spec:
      securityContext:
        runAsUser: 2001
        runAsGroup: 2001
      initContainers:
        - name: setup-htdl
          securityContext:
            runAsUser: 0
            runAsGroup: 0
          image: {{ .Values.images.cs_ops }}
          imagePullPolicy: Always
          command:
            - /usr/local/bin/cs_ops.sh
            - setup
            - all
          volumeMounts:
          - mountPath: /home/cs-user
            name: home-volume
          - mountPath: /tools
            name: tools-volume
          - mountPath: /data
            name: data-volume
          - mountPath: /local
            name: ephemeral-volume
        - name: restore-home
          image: {{ .Values.images.cs_ops }}
          imagePullPolicy: Always
          env:
          - name: SYNC_SERVER
            value: {{ .Values.sync_server }}
          - name: SYNC_USER
            value: {{ .Values.user }}
          command:
            - /usr/local/bin/tini
            - --
            - /usr/local/bin/cs_ops.sh
            - restore
            - home
          volumeMounts:
          - mountPath: /home/cs-user
            name: home-volume
          - mountPath: /configmap
            name: cs-config-volume
        - name: restore-tools
          image: {{ .Values.images.cs_ops }}
          imagePullPolicy: Always
          env:
          - name: SYNC_SERVER
            value: {{ .Values.sync_server }}
          - name: SYNC_USER
            value: {{ .Values.user }}
          command:
            - /usr/local/bin/tini
            - --
            - /usr/local/bin/cs_ops.sh
            - restore
            - tools
          volumeMounts:
          - mountPath: /tools
            name: tools-volume
          - mountPath: /configmap
            name: cs-config-volume
        - name: restore-data
          image: {{ .Values.images.cs_ops }}
          imagePullPolicy: Always
          env:
          - name: SYNC_SERVER
            value: {{ .Values.sync_server }}
          - name: SYNC_USER
            value: {{ .Values.user }}
          command:
            - /usr/local/bin/tini
            - --
            - /usr/local/bin/cs_ops.sh
            - restore
            - data
          volumeMounts:
          - mountPath: /data
            name: data-volume
          - mountPath: /configmap
            name: cs-config-volume
      containers:
        - name: code-server
          image: {{ .Values.images.codeserver }}
          imagePullPolicy: Always
          env:
          - name: TZ
            value: Etc/UTC
          - name: SYNC_SERVER
            value: {{ .Values.sync_server }}
          - name: SYNC_USER
            value: {{ .Values.user }}
          command:
            - /usr/local/bin/tini
            - --
            - /usr/local/bin/entrypoint.sh
            - /usr/local/bin/code-server
            - --bind-addr
            - "0.0.0.0:8443"
            - --disable-telemetry
            - --auth
            - "none"
            - --app-name
            - code-server-for-{{ .Values.user }}
          volumeMounts:
          - mountPath: /home/cs-user
            name: home-volume
          - mountPath: /tools
            name: tools-volume
          - mountPath: /data
            name: data-volume
          - mountPath: /local
            name: ephemeral-volume
          - mountPath: /configmap
            name: cs-config-volume
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          ports:
            - containerPort: 8443
          livenessProbe:
            periodSeconds: 60
            timeoutSeconds: 2
            httpGet:
              path: /
              port: 8443
          readinessProbe:
            periodSeconds: 60
            timeoutSeconds: 2
            httpGet:
              path: /
              port: 8443
{{- if .Values.node_label }}
      nodeSelector:
        "otvl-agent": {{ .Values.node_label }}
{{- end }}
      volumes:
      - name: home-volume
        emptyDir:
      - name: tools-volume
        emptyDir:
      - name: data-volume
        emptyDir:
      - name: ephemeral-volume
        emptyDir:
      - name: cs-config-volume
        configMap:
          name: {{ .Release.Name }}-cs-cmap
      tolerations:
      - key: "agent-deploy"
        value: "true"
        effect: "NoExecute"
      restartPolicy: Always
