{{- if .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-production
spec:
  tls:
    - hosts:
        - {{ include "otvl-ctr-ingress-hostname" . }}
      secretName: {{ .Release.Name }}
  rules:
    - host: {{ include "otvl-ctr-ingress-hostname" . }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name:  {{ .Release.Name }}-proxy
                port:
                  number: 5000
{{- end }}
