apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-proxy
spec:
  selector:
    app.kubernetes.io/name: {{ .Release.Name }}-proxy
  ports:
    - name: router-port
      port: 5000
      protocol: TCP
