apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-reg
spec:
  selector:
    app.kubernetes.io/name: {{ .Release.Name }}-reg
  ports:
    - name: "reg-port"
      port: 5000
      protocol: TCP
