images:
  ows_app: t-ctr.otvl.org/ows-app:0.0.1
  traefik: traefik:v3.4
resources:
  requests:
    cpu: "250m"
    memory: 256Mi
  limits:
    cpu: "500m"
    memory: 512Mi
ingress:
  enabled: true
  # host: ows-app.example.com, defaults to <release-name>.example.com
